### ISSUE TITLE
Mod is crashing my game

### ISSUE THREAD

**Issue by ghost** [Gegy/colored-lights#16] opened 2021-08-19 01:39 UTC
btw this is a copy from my curseforge comment on this mod, I would love to use this mod with my builds as it would make them look so good
This mod isnt working for me, not sure if its compatability with other mods or something like that idk how to read these things. Heres the crash https://pastebin.com/rA4P73kx

**Comment by Nathan22211** [comment] 2021-08-19 09:59
it's a sodium conflict, this mod crashes even with indium

**Comment by ghost** [comment] 2021-08-19 14:40
Im using iris and sodium extras so that should be where the problem is coming from

**Comment by Gegy** [comment] 2021-11-25 08:01
Yep! This is a Sodium conflict- thanks Nathan. 🙂 
Closing this for now as duplicate of #11 :)

**Closed as completed by Gegy** 2021-11-25 08:01 UTC
Labels: duplicate
