### ISSUE TITLE
Mod on 1.17.1 is not working.

### ISSUE THREAD

**Issue by Venya203** [Gegy/colored-lights#21] opened 2022-01-06 19:46 UTC
If i launch the game with this mod it crashes. i Use **colored-lights-1.0.3.jar**. But if i drag it from the mods folder Minecraft is starts normally _not crashes_.

**Comment by hibiii** [comment] 2022-01-06 19:48
Could you post a crash log, please?

**Comment by Venya203** [comment] 2022-01-06 19:59
[crash-2022-01-06_20.16.38-client.txt](https://github.com/Gegy/colored-lights/files/7824388/crash-2022-01-06_20.16.38-client.txt)

**Comment by hibiii** [comment] 2022-01-06 20:19
That's because Colored Lights doesn't work with Optifine, Sodium or Canvas for that matter.

Colored Lights 1.1.0 prevents you from shooting yourself in the foot by telling Fabric itself it breaks Optifine before any crashes happen, but that's for 1.18.x.

**Comment by Venya203** [comment] 2022-01-06 20:20
Thank you.

**Comment by Gegy** [comment] 2022-01-08 10:21
Going to close as duplicate of #11- thank you @Hibiii for the support here. 😊

**Closed as completed** 2022-01-08 10:21 UTC
Labels: duplicate
